"""Added category and product table

Revision ID: 0001
Revises: 
Create Date: 2024-08-19 11:15:08.938514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_category',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shop_category')),
    sa.UniqueConstraint('name', name=op.f('uq_shop_category_name'))
    )
    op.create_index(op.f('ix_shop_category_id'), 'shop_category', ['id'], unique=True)
    op.create_table('shop_product',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shop_product')),
    sa.UniqueConstraint('name', name=op.f('uq_shop_product_name'))
    )
    op.create_index(op.f('ix_shop_product_id'), 'shop_product', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_product_id'), table_name='shop_product')
    op.drop_table('shop_product')
    op.drop_index(op.f('ix_shop_category_id'), table_name='shop_category')
    op.drop_table('shop_category')
    # ### end Alembic commands ###
